---
# defaults file for install_system_ansible

ansible_packages:
  - ansible
  - python3
  - python3-pip
  - python3-hvac

ansible_lint_packages:
  - python3-detect-secrets
  - pre-commit

ansible_runtime_packages:
  - sshpass
