- name: Configure system Ansible runtime environment for development
  hosts: ansible-dev-container
  become: true

  tasks:
    - name: Configure dev runtime environment
      ansible.builtin.include_role:
        name: deamen.general.config_dev_runtime_env
    
    - name: Configure Ansible runtime environment
      ansible.builtin.include_role:
        name: deamen.general.config_ansible_runtime_env