- name: Install development packages
  hosts: all:!localhost
  become: true

  tasks:
    - name: Install development packages
      ansible.builtin.include_role:
        name: deamen.general.install_dev_packages
