---
- name: Converge (molecule dummy)
  hosts: molecule
  gather_facts: no
  tasks:
    - name: Dummy converge - display message
      ansible.builtin.debug:
        msg: "Converge placeholder: running on 'molecule' group"
