namespace: "deamen"

# The name of the collection. Has the same character restrictions as 'namespace'
name: "podman"

# The version of the collection. Must be compatible with semantic versioning
version: "1.0.2"

readme: README.md

authors:
  - github.com/deamen

description: >
  Ansible collection to manage and set up Podman: install packages, configure
  registries, manage containers/images, and integrate with systemd (rootless
  and rootful).

license:
  - GPL-3.0-or-later

tags: ["linux", "containers", "podman", "automation"]

dependencies:
  deamen.general: ">=1.0.0,<2.0.0"

# The URL of the originating SCM repository
repository: https://github.com/deamen/ansible_collections

# The URL to any online docs
documentation: https://github.com/deamen/ansible_collections/blob/master/collections/ansible_collections/deamen/podman/README.md

# The URL to the homepage of the collection/project
homepage: https://github.com/deamen/ansible_collections/tree/master/collections/ansible_collections/deamen/podman

# The URL to the collection issue tracker
issues: https://github.com/deamen/ansible_collections/issues

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
