---
namespace: deamen
name: ansible
version: 1.0.2
readme: README.md
authors:
  - Song Tang <stang@mmz.au>
description: Install and configure Ansible
license:
  - GPL-3.0-or-later
tags:
  - application
dependencies: {}
repository: https://github.com/deamen/ansible_collections
documentation: https://github.com/deamen/ansible_collections/tree/master/collections/ansible_collections/deamen/ansible/docs
homepage: https://github.com/deamen/ansible_collections/tree/master/collections/ansible_collections/deamen/ansible
issues: https://github.com/deamen/ansible_collections/issues
build_ignore: []
