# SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  author: github.com/deamen
  description: Install Podman and related packages; prepare host for running containers (rootful and rootless).
  license: GPL-3.0-or-later
  min_ansible_version: "2.15.0"

  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - podman
    - containers
    - linux
    - systemd

dependencies: []
