objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    deploy_certificate:
      description: Deploy a certificate and key to specified locations
      name: deploy_certificate
      namespace: ''
      version_added: 1.1.0
    deploy_private_ca:
      description: Deploy a private CA certificate to a Linux server
      name: deploy_private_ca
      namespace: ''
      version_added: 1.0.0
    gen_cert_from_vault:
      description: Generate a certificate using HashiCorp Vault PKI backend
      name: gen_cert_from_vault
      namespace: ''
      version_added: 1.3.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 1.3.0
