---
galaxy_info:
    author: Song Tang
    description: Deploy Microsoft Copilot CLI installation script to target hosts and execute it.
    company: Yobibyte
    license: GPL-3.0-or-later

    min_ansible_version: "2.14"

    galaxy_tags: []

dependencies: []
