---
# tasks file for config_gpg
- name: Validate required variables
  ansible.builtin.fail:
    msg: config_gpg_user is required, and config_gpg_fingerprint is required when config_gpg_import_key is true.
  when: >-
    (config_gpg_user | length == 0) or
    ((config_gpg_import_key | bool) and (_config_gpg_fingerprint | length == 0))

- name: Ensure GPG directory exists
  ansible.builtin.file:
    group: '{{ config_gpg_user }}'
    mode: '0700'
    owner: '{{ config_gpg_user }}'
    path: '/home/{{ config_gpg_user }}/.gnupg'
    state: directory
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'

- name: Deploy gpg-agent.conf
  ansible.builtin.template:
    dest: '/home/{{ config_gpg_user }}/.gnupg/gpg-agent.conf'
    group: '{{ config_gpg_user }}'
    mode: '0600'
    owner: '{{ config_gpg_user }}'
    src: gpg-agent.conf.j2
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'

- name: Import GPG key and configure owner trust
  ansible.builtin.include_tasks:
    file: import_gpg_key.yml
  when: _config_gpg_fingerprint | length > 0
