---
# tasks file for config_gpg
- name: Ensure GPG directory exists
  ansible.builtin.file:
    group: '{{ config_gpg_user }}'
    mode: '0700'
    owner: '{{ config_gpg_user }}'
    path: '/home/{{ config_gpg_user }}/.gnupg'
    state: directory
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'

- name: Deploy gpg-agent.conf
  ansible.builtin.copy:
    dest: '/home/{{ config_gpg_user }}/.gnupg/gpg-agent.conf'
    group: '{{ config_gpg_user }}'
    mode: '0600'
    owner: '{{ config_gpg_user }}'
    src: gpg-agent.conf
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'

- name: Check if GPG key is already imported
  ansible.builtin.command:
    cmd: 'gpg --list-secret-keys --with-colons {{ config_gpg_fingerprint }}'
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'
  changed_when: false
  failed_when: false
  register: _config_gpg_key_check

- name: Check if GPG key has ultimate trust
  ansible.builtin.shell:
    cmd: "set -o pipefail && gpg --export-ownertrust | grep {{ config_gpg_fingerprint }} | grep ':6'"
    executable: /bin/bash
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'
  changed_when: false
  failed_when: false
  register: _config_gpg_trust_check

- name: Set facts for GPG import variables
  ansible.builtin.set_fact:
    _config_gpg_import:
      ownertrust: '{{ _config_gpg_trust_check.rc != 0 }}'
      secret_key: '{{ _config_gpg_key_check.rc != 0 }}'

- name: Import GPG private key
  ansible.builtin.command:
    cmd: 'gpg --batch --import {{ config_gpg_private_key_path }}'
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'
  changed_when: _config_gpg_import.secret_key
  notify: Remove private GPG key file
  when: _config_gpg_import.secret_key

- name: Create ownertrust file
  ansible.builtin.copy:
    content: |
      # This file is automatically generated by ansible-playbook.
      # Do not edit this file manually.
      {{ config_gpg_fingerprint }}:6
    dest: '/home/{{ config_gpg_user }}/.gnupg/owntrust.txt'
    group: '{{ config_gpg_user }}'
    mode: '0600'
    owner: '{{ config_gpg_user }}'
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'
  when: _config_gpg_import.ownertrust

- name: Import ownertrust file
  ansible.builtin.command:
    cmd: 'gpg --batch --import-ownertrust /home/{{ config_gpg_user }}/.gnupg/owntrust.txt'
  become: true
  become_method: ansible.builtin.sudo
  become_user: '{{ config_gpg_user }}'
  changed_when: _config_gpg_import.ownertrust
  notify: Remove ownertrust file
  when: _config_gpg_import.ownertrust
