name: Release deamen.podman

on:
  push:
    tags:
      - 'release_deamen.podman_v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    uses: ./.github/workflows/ansible_collection_base_workflow.yml
    with:
      collection_path: collections/ansible_collections/deamen/podman
    secrets:
      ANSIBLE_GALAXY_APIKEY: ${{ secrets.ANSIBLE_GALAXY_APIKEY }}
