name: Run Ansible lint
on:
  pull_request:
    branches:
      - master
    paths:
      - 'collections/ansible_collections/**'

jobs:
  build:
    name: Run Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v26.3.0
        with:
          args: "deamen/"
          setup_python: "true"
          working_directory: "collections/ansible_collections"
          requirements_file: "requirements.yml"
